### ISSUE TITLE
Logout functionality is broken in the example project

### ISSUE THREAD

**Issue by nurpax** [nurpax/snaplet-sqlite-simple#17]
I noticed that the "logout" handler in the example project doesn't work after upgrading to snap-1.0.

I found this out in a larger project where it fails the same way.  It however does work in the snap-templates default project.  In the snap-templates project, logout is able to logout the user and redirect to /.  In snaplet-sqlite-simple example project, the logout link just returns an empty reply from the server:

```
curl http://localhost:8000/logout
curl: (52) Empty reply from server
``` 

The code for the logout route is the same in both snap-templates and snaplet-sqlite-simple/example.  But snap-templates uses the JSON auth backend, so maybe that works differently.

I guess an exception is thrown somewhere but unfortunately it gets silently thrown away and not logged.

@sigrlami You haven't by any chance come across this?

**Comment by nurpax** [comment]
Fixed by 4ad82c94ca258f1680600b45fd7f0c866b306eff

**Comment by nurpax** [comment]
I have no idea why that omission didn't trigger a compiler warning though.

**Comment by sigrlami** [comment]
@nurpax interesting. No I didn't notice it, will check. I think it's because you're actually updating default data, not creating a new one.

**Comment by nurpax** [comment]
I thought this would be creating a completely new AuthManager

```
    return AuthManager
      { backend = manager
      , session = sess
      , activeUser = Nothing
      , minPasswdLen = asMinPasswdLen authSettings
      , rememberCookieName = asRememberCookieName authSettings
      , rememberCookieDomain = Nothing
      , rememberPeriod = asRememberPeriod authSettings
      , siteKey = key
      , lockout = asLockout authSettings
      , randomNumberGenerator = rng
      }
```
